name: Build and Deploy (Dev)

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{branch}}
            type=raw,value=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update deploy-dev branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin master:deploy-dev 2>/dev/null || git checkout -b deploy-dev
          git checkout deploy-dev

          git reset --hard origin/${{ github.ref_name }}

          sed -i "s|ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:.*|ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}|g" docker-compose.yml

          git add docker-compose.yml
          git commit -m "Dev Deploy: Update for branch ${{ github.ref_name }}" 2>/dev/null || echo "No changes to commit"
          git push origin deploy-dev --force

      - name: Trigger Portainer Webhook
        if: success()
        run: |
          curl -X POST "${{ secrets.PORTAINER_WEBHOOK_DEV }}" || echo "Webhook trigger failed"
